
language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"
  - "4.2.6"
  - "4"
env:
  - CXX=g++-4.8
add-ons:
  api:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm install -g grunt
script:
  - grunt